name: CI/CD action
on:
  push:
    branches: [main]

jobs:
  testing:
    runs-on: ubuntu-latest

    env:
      PG_NAME: ${{secrets.PG_NAME}}
      PG_PASSWORD: ${{secrets.PG_PASSWORD}}
      PG_USER: ${{secrets.PG_USER}}
      PG_PORT: ${{secrets.PG_PORT}}
      PG_HOST: ${{secrets.PG_HOST}}

    services:
      postgres_main:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{env.PG_USER}}
          POSTGRES_DB: ${{env.PG_NAME}}
          POSTGRES_PASSWORD: ${{env.PG_PASSWORD}}
          POSTGRES_PORT: ${{env.PG_PORT}}
          POSTGRES_HOST: ${{env.PG_HOST}}
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 5s
          --health timeout 5s
          --health-retries 5

    steps:
      - name: Проверить изменения
        uses: actions/checkout@v2

      - name: Установка пайтон
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Установка зависимостей
        run: pip install -r requirements.txt

      - name: Линтер
        run: flake8 webpython --exclude migrations --ignore E501,F401,E302,W293,W391,W292

      - name: Тесты
        run: python webpython/manage.py test
        env:
          PG_USER: ${{env.PG_USER}}
          PG_DB: ${{env.PG_NAME}}
          PG_PASSWORD: ${{env.PG_PASSWORD}}
          PG_PORT: ${{env.PG_PORT}}
          PG_HOST: ${{env.PG_HOST}}


  deploy:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - name: Деплой
        uses: appleboy/ssh-action@master
        with:
          host: 79.174.80.252
          username: ubuntu
          password: 12345
          scripts: |
            cd Web-server-demo-Netology/webpython
            git pull
            sudo systemctl restart gunicorn1
